<a href="https://colab.research.google.com/github/Ali-mohammadi-design/ML-practice/blob/main/L.R12-fitting%20model%20and%20testing%20it%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("heellllloooo")

heellllloooo


In [24]:
import pandas as pd
import numpy as np

data=pd.read_excel("Data.xlsx")

In [ ]:
data.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [19]:
x=data.iloc[:,0:3].values

In [ ]:
type(x)

numpy.ndarray

In [20]:
x

array([[  14.96,   41.76, 1024.07],
       [  25.18,   62.96, 1020.04],
       [   5.11,   39.4 , 1012.16],
       ...,
       [  31.32,   74.33, 1012.92],
       [  24.48,   69.45, 1013.86],
       [  21.6 ,   62.52, 1017.23]])

In [6]:
y=data.iloc[:,4].values

In [7]:
y

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=0)

In [10]:
from sklearn.linear_model import LinearRegression
# we have imported the linear regression class
model=LinearRegression()
 # we have made a class
 

In [11]:
#train the model:
model.fit(x_train,y_train)

LinearRegression()

In [15]:
#testing the model:
y_predict=model.predict(x_test)
y_predict

array([431.26439822, 460.84793971, 466.82423391, ..., 471.21894983,
       442.50872157, 462.00539005])

In [32]:
#predicting a new data:

In [28]:
x_enter=np.array([[15,40,1000]])

In [29]:
type(x_enter)

numpy.ndarray

In [31]:
y_predict2=model.predict(x_enter)
y_predict2

array([464.58977987])